name: Build, Push & Deploy Frontend Docker Image

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - uses: actions/checkout@v3

      # Step 2: Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/shrikarpatil/frontend:latest

      # Step 4: Create PEM file from secret
      - name: Create PEM file
        run: |
          echo "${{ secrets.EC2_KEY }}" > mykey.pem
          chmod 600 mykey.pem

      # Step 5: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key_path: mykey.pem
          port: 22
          debug: true
          script: |
            sudo docker pull ghcr.io/shrikarpatil/frontend:latest
            sudo docker stop frontend || true
            sudo docker rm frontend || true
            sudo docker run -d -p 3000:3000 --name frontend ghcr.io/shrikarpatil/frontend:latest
